### ISSUE TITLE
Basic audio support

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#143]
Low priority. No idea how to do it sanely. Only cutting is actually needed.

**Comment by Ken-g6** [comment]
I find VapourSynth absolutely useless without basic audio support.  Please elevate the priority on this.

It seems there are three steps needed:
1. Audio needs to be retrieved from FFMS2.  There seems to be a function FFMS2_GetAudio(), but I'm having trouble finding details on it.
1. Audio needs to be processed.  @dubhater has an audio processing plugin. https://github.com/dubhater/vapoursynth-damb
1. Audio needs to be sent out interleaved with the video.  I have no idea how to do this.

**Comment by invisiblearts** [comment]
Dealing with audio should not be a big problem within vapoursynth itself; just think about how it's done in commercial non-linear editing solutions. Adding an `AudioNode` type should be fine.

Sending out audio, however, is another story. Interleaving the audio with the video is not necessarily a good idea. IMHO we can just use named pipe, which should be cross-platform enough. Outputting the data either in two files or in a muxed stream media file might do. Correct me if I am wrong, but this may even replace avfs.

**Comment by stuxcrystal** [comment]
I agree, interleaving audio with video is a bad idea. In the IRC there was a discussion about video-props instead of frame-props.

Adding video-props would allow to store the audio-clip to a video-clip without interleaving it.

**Comment by mleise** [comment]
@invisiblearts I agree on the non-interleaving but personally prefer support built into ffmpeg instead of pipes or sockets because that instantly enables VapourSynth in everything using ffmpeg for loading videos. Thumbnailers, media players, x264, even Audacity just for the lulz. The ideas don't exclude each other though, so once audio is in the API, both solutions can be pursued.
On Windows, you can associate AviSynth scripts with MPC Home Cinema or ffplay for instant playback with audio or use them directly as input for ffmpeg. That is _very_ convenient.

@myrsloik Support for only cutting would preclude important use cases. In AviSynth most filters that work with multiple clips simultaneously would use the audio from the first clip, but those that change video fps, create transitions or do non-linear editing, process audio, too. Audio and video have their separate filter chains and if either one is not requested, it lays idle. You can re-render the audio without the video filters for example. There are a couple audio only filters like an equalizer, volume adjustment, delay, joining/splitting mono/stereo or a wrapper around SOX while others (i.e. Reverse()) can filter both audio and video.

Thinking ahead it may be useful if the solution was be general enough to be extended to multiple audio languages, subtitles and anything else that can be a track.

**Comment by myrsloik** [comment]
Implemented in the doodle1 branch. See doom9 thread for further discussions.
