### ISSUE TITLE
'module' object has no attribute 'get_core'

### ISSUE THREAD

**Issue by an3k** [vapoursynth/vapoursynth#208]
```
root@encoder:~# python3.4
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth as vs
>>> c = vs.get_core()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'get_core'
>>>
```
I have absolutely no clue what's going on or where to look at.

**Comment by dubhater** [comment]
What attributes does it have? ``dir(vs)`` will tell you.

**Comment by an3k** [comment]
>>> dir(vs)
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

**Comment by dubhater** [comment]
Very strange. Print them, please. (``print(vs.doc)``, etc)

**Comment by an3k** [comment]
>>> print(vs.doc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'doc'
>>> print(vs.__doc__)
None
>>> print(vs.__loader__)
<_frozen_importlib._NamespaceLoader object at 0x7fa00ee824e0>
>>> print(vs.__name__)
vapoursynth
>>> print(vs.__package__)
vapoursynth
>>> print(vs.__path__)
_NamespacePath(['/root/vapoursynth'])
>>> print(vs.__spec__)
ModuleSpec(name='vapoursynth', loader=None, origin='namespace', submodule_search_locations=_NamespacePath(['/root/vapoursynth']))

**Comment by an3k** [comment]
Gitter? IRC?

**Comment by dubhater** [comment]
I guess you have a folder ``/root/vapoursynth``? Maybe rename it and try again?

**Comment by an3k** [comment]
Nope :(

http://pastebin.com/c70NYxMq

**Comment by an3k** [comment]
Nope :(

http://pastebin.com/tCf1gyni

**Comment by dubhater** [comment]
That's good! Try with
```
PYTHONPATH=/usr/local/lib/python3.4/site-packages python3.4
```

**Comment by an3k** [comment]
```root@encoder:~# PYTHONPATH=/usr/local/lib/python3.4/site-packages python3.4
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth as vs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libvapoursynth.so: cannot open shared object file: No such file or directory
>>>
```

**Comment by dubhater** [comment]
Right.
```
PYTHONPATH=/usr/local/lib/python3.4/site-packages LD_LIBRARY_PATH=/usr/local/lib python3.4
```

**Comment by an3k** [comment]
Uh, it works.
```
root@encoder:~# PYTHONPATH=/usr/local/lib/python3.4/site-packages LD_LIBRARY_PATH=/usr/local/lib python3.4
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth as vs
>>> c = vs.get_core()
>>> print(c.version())
VapourSynth Video Processing Library
Copyright (c) 2012-2015 Fredrik Mellbin
Core R30
API R3.4
Options: -

>>>
```
Do I have to start vapoursynth like this all the time? Isn't there something like `./vapoursynth myscript.vpy`?

**Comment by an3k** [comment]
I'm sorry for all these stupid questions but I simply wanted to get two very basic AviSynth scripts running on Linux but instead I tried to get vapoursynth running the last two days. Now it runs but I'm still very far from firing up that 12-core Xeon :(

**Comment by dubhater** [comment]
I think running ldconfig will remove the need for ``LD_LIBRARY_PATH``.

And of course you can export ``PYTHONPATH`` in your shell's configuration.

You can also write a shell script that runs vspipe with these variables.

You can also pass ``--prefix=/usr`` to configure so that everything is installed in the standard locations. Then you shouldn't need any of these variables.

**Comment by splinter98** [comment]
This seems to be a common issue when using locally compiled python modules coupled with using python provided through package management (i.e. installing python using apt-get or aptitude). Debian (and derivatives like Ubuntu), explicitly disable the use of site-packages and put their packages in dist-packages. From memory they cite something about the changes they do to python is to do with suitable for production, but recognise it's not for developers (because who else other than developers would compile code - and surely they would compile everything from source anyway...)

ref: https://leemendelowitz.github.io/blog/how-does-python-find-packages.html

**Comment by myrsloik** [comment]
Is there any sane way to make this work just work? Or are there saner distros that don't do this?

**Comment by an3k** [comment]
If one uses the debian / ubuntu package manager: No. Because of that I've made a build_script for Ubuntu (which should work for Debian too) that will install all necessary packages (eg. python-dev), download the required software (eg YASM or ZIMG) and compile it into the users home directory so it doesn't interfere with the system.
The intended use is to setup a computer running the same environment (eg. Ubuntu 14.04.2 on x86) just for building the software from source and then move the binaries, libraries, etc. onto the machine you actually want to use it. That way our machine keeps very clean. If you want to get rid of VapourSynth you simply delete the user OR the directories.

**Comment by dubhater** [comment]
Doesn't ``--prefix=/usr`` avoid all these problems?

**Comment by an3k** [comment]
Stop! You don't compile stuff yourself and install it system-wide. You'll never ever be able to clean that if there is an error or just because you want.

**Comment by an3k** [comment]
@myrsloik Because of the issues I wrote a simple bash script that a) installs the required packages, b) downloads the sources for eg. YASM, VapourSynth, etc. and compiles each of it and finally installs everything into $HOME.
If you want users to execute a simple ````./setup.vapoursynth.sh```` command to get vapoursynth running with all its dependencies we can work together to get my current (post-alpha) script past perfection :)

**Comment by dubhater** [comment]
Indeed, you're supposed to compile stuff yourself, make a distro-specific package, and install that system-wide.

**Comment by splinter98** [comment]
Default prefix should be /usr/local for custom builds.

Been doing some digging about this, and it seems adding (if I understand correctly) --install-layout=deb should make things work with the distribution install python. But this will only work with debian derivative (I can't find if this ever made upstream and haven't tested.)

Using a a custom build of python avoids this (but undesirable). Really Debian/Ubuntu is set up to really to provide binaries rather than compile yourself.

ref: https://lists.ubuntu.com/archives/ubuntu-devel/2009-February/027439.html

**Comment by an3k** [comment]
Well, if you have to compile it yourself you don't need to make a distro-specific package too. Once you have it compiled you already have a running installation and as long as you don't want other users on the same machine to use it themselves too there's no need for a package. Especially because you can't update it through the package manager.

My build script (which should be run on a BuildHost so you don't waste your productive machine with packages you only need to build/compile from source) creates a tar.xz (or tar.bz2) that is fully portable to other machines running the same distri (eg. Ubuntu 14.04.3) and arch (eg. x86).

**Comment by an3k** [comment]
The most simple solution is ````export PYTHONPATH=path/to/python/packages```` in your .profile file

**Comment by an3k** [comment]
Btw. on my Ubuntu 14.04.3 Python3.4 does this:
````
vapoursynth@server:~$ python3.4
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/home/vapoursynth/lib/python3.4/site-packages', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/usr/lib/python3.4/lib-dynload', '/usr/lib/python3/dist-packages']
>>>
````
It does NOT search in /usr/local/lib* by default. In the above paste it (additionally) searches in /home/vapoursynth/lib/python3.4/site-packages because I told it to do so (using the export command)

**Comment by splinter98** [comment]
These are still workarounds - the question is can we implement something into the make build that installs it into the correct directory? Ubuntu (and even Debain in this instance) are very widely used linux distros so it's easy to argue that something should be in place that 'just works'

It's also worth asking why have they done something seemingly insane? The main reason they use dist-utils over site-packages is because if python gets updated then it will break Vapoursynth because of the same reasons we only distribute a single version of Vapoursynth on Windows.

**Comment by an3k** [comment]
You have to use a workaround. While you can force the make build to install VS into /usr/lib/python3/dist-packages you absolutely should NOT because that really can break functionality. Simply append to the .profile (if neither ~/.bash_profile nor ~/.bash_login exist) the export command I posted above and everything is fine.

**Comment by splinter98** [comment]
Agreed, if we want to install direct into dist-packages we should be distributing .deb packages.

Putting PYTHONPATH in to your .profile I'd argue is almost if not just as bad as as installing directly to dist-utils. yes when python gets upgraded it doesn't touch the installation but it still breaks.

If you've written a build script that's designed to be portable then it should really produce a .deb file that can then be installed and managed properly.

Ideally we should setup a CI server that builds all of these different flavours on each release, and recommended using those to solve these issues. Compiling manually would then be for development use.

**Comment by an3k** [comment]
Regarding packages there are three solutions:
1) Get your package into the official debian / ubuntu repo. Most effort but users just have to install it. (apt-get install vapoursynth)
2) Create your own PPA. Less effort than 1) but users have to manually add the PPA to their sources. (I never added any PPA. I don't trust them much)
3) Create your own package using checkinstall. Least effort. Works but probably will break stuff on completely other machines. Author of checkinstall clearly says "packages are not for redistribution".

Regarding the PYTHONPATH. Neither export nor installing into dist-packages cause Python to auto-load these so Python would not crash automatically but only when the user tries to import vapoursynth. However when you use PYTHONPATH you can use site-packages and the advantage here is that you have the "could break something"-version separated from the "maintained by ubuntu/debian and thus always working"-versions located in dist-packages.
But I fully agree that both solutions aren't that suitable for enduser-mass-production :)

Well, creating a deb file is "easy", see checkinstall. The downside is that it is NOT for redistribution because it doesn't care about dependencies, etc. It's missing too much meta-data. It's just like an archive with some additional information. A real deb file causes much more work to create (check dependencies, collisions, etc.) and my build_script is really far from that. It's more suited for developers who have a second machine running the same OS and Arch and who don't want to build on their main machine but on the second (virtual) machine and just copy&paste the necessary files from the buildhost onto the productive machine. My builds are completely independent from the system-wide installed libs and bins. Everything required (except python) is installed in /home/username/ and if you want to get rid of it simply delete the user or the directories.

**Comment by splinter98** [comment]
1 & 2 are just different ways to distribute packages, with different requirements on who maintains them. official currently unsuitable for vapoursynth due to no backwards compatibility guarantees. PPA however would require someone in the community to maintain it.

Check install makes no sense for redistribution.

Packages in dist-pacakages aren't loaded automatically either. Only when they're imported like in site-packages. So python would continue to work normally either way. Packages in dist-packages should have updated versions ready when there is an upgrade to python. (or at least can block python upgrades if they don't exist).

Autotools has hooks to support generating debian packages, (and most likely RPM too) so for generating the deb file I would go down that route, (and from there we can specify what dependencies we used).

It's great you have a build script that can generate 'portable' versions of vapoursynth. But if we're talking about the 'end user experience' then that doesn't solve that issue much. An arguably more portable way would be to provide a docker container that has everything packaged up ready to go and would be completely OS independent.
