### ISSUE TITLE
Linux: vsscript_init fails

### ISSUE THREAD

**Issue by chainikdn** [vapoursynth/vapoursynth#227]
The error occurs at the PyImport_Import call:

`ImportError: /usr/lib/python3/dist-packages/vapoursynth.so: undefined symbol: PyExc_SystemError
`

Here's [a workaround](https://mail.python.org/pipermail/new-bugs-announce/2008-November/003322.html).

In our case calling
`dlopen("libpython3.4m.so.1", RTLD_LAZY|RTLD_GLOBAL);`
before vsscript_init() fixes the issue.

It seems like a Linux-only issue, the very same code works just fine in both Windows and OS X.

**Comment by dubhater** [comment]
That's a Python design issue, or quirk, or whatever you want to call it, not a VapourSynth bug. Python binary modules, such as vapoursynth.so, require symbols from libpython. If you're dlopening libpython, whether directly, or indirectly through libvapoursynth-script, you need to use RTLD_GLOBAL.

The same code works in OS X because "If neither RTLD_GLOBAL nor RTLD_LOCAL is specified, the default is RTLD_GLOBAL." In Windows Python binary modules have to link libpython because of Windows reasons, so the symbols are available.

**Comment by chainikdn** [comment]
I totally agreed. However for me, as a Vapoursynth user w/o any knowledge how it works "under the hood", it took a long time to figure out what's going on - to be more specific "why the hell the very same call to vsscript_init() works in mpv's filter but doesn't in VLC's plugin".

May be you could add a workaround for this in the initialization?

**Comment by dubhater** [comment]
Maybe I could add a note to the documentation.
