### ISSUE TITLE
Debian "make" Problems

### ISSUE THREAD

**Issue by Infiziert90** [vapoursynth/vapoursynth#253]
Hiho, 

System: Debian Jessie 64bit

i get tons of errors and warnings in the newest Build again ... 
./configure runs without any warning or error
but make ...
http://sprunge.us/OEff

**Comment by dubhater** [comment]
You probably need ffmpeg instead of libav. Alternatively, pass ``--disable-subtitle`` to configure.

**Comment by Infiziert90** [comment]
configure: WARNING: unrecognized options: --disable-subtitle

**Comment by Infiziert90** [comment]
thx worked for me ...

and i'm using ffmpeg 
ffmpeg version 3.2.2-1~bpo8+1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)

**Comment by dubhater** [comment]
I have ffmpeg 3.2.2 as well (compiled from https://ffmpeg.org/releases/ffmpeg-3.2.2.tar.xz, unpatched). The subtext plugin compiled fine.

Does ``pkg-config --cflags libavutil`` give you the right path?

**Comment by Infiziert90** [comment]
Nop ... it shows me a empty line

**Comment by dubhater** [comment]
An empty line probably means the pkg-config file says ``-I/usr/include``. pkg-config doesn't print that because the compiler will look in that folder anyway.

If your ffmpeg package was installed in /usr and /usr/include/libavutil belongs to it, then I don't know what's wrong. If your ffmpeg package was installed elsewhere, then you need to invoke VapourSynth's configure like this: ``PKG_CONFIG_PATH='/your_ffmpeg_packages_libdir/pkgconfig' ./configure``

**Comment by Infiziert90** [comment]
root@Debian-82-jessie-64-LAMP ~/# whereis libavutil
libavutil: /usr/include/libavutil

its the same path ... so i think its a bug from vapoursynth 
also its not a problem from me alone, ubuntu server shows the same issue with subtitle renderer

**Comment by Infiziert90** [comment]
A clean build of the latest stable release of ffmpeg solves my problem. It seems to be a problem with the ffmpeg build in the Debian/Ubuntu repository.

**Comment by Infiziert90** [comment]
Actually I built the latest snapshot, not the release. No idea if it would have worked with the release, too.
