### ISSUE TITLE
Document __vapoursynth__-module name in vsscript based programs.

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#323]
In [vapoursynth.pyx#1821](https://github.com/vapoursynth/vapoursynth/blob/master/src/cython/vapoursynth.pyx#L1821) the string `__vapoursynth__` is stored inside the `__name__`-variable. This might cause unexpected behavious when a user tries to use the following code:

```py
if __name__ == "__main__":
    doStuff()
```

The code above would not work since, as I just mentioned, inside vspipe, the value assigned to `__name__` is `__vapoursynth__`.

Please document this behaviour so people won't stumble over it.

**Comment by myrsloik** [comment]
Would it be reasonable to simply change it to __main__ instead?

**Comment by splinter98** [comment]
The reason I made it `__vapoursynth__` instead of `__main__` is for when you want to know when you're being executed are you inside vsscript or standard python. This meant I could write a main function that returns the processed clip and either print out the format (useful for debugging a complex script) or set up the output to be processed. See the original pull request (#115) for the example idiom I was proposing.

I'm not majorly opposed to changing it to `__main__` as long as there is another way to detect if you're inside vapoursynth or not. However I think having different behaviour inside vsscript is beneficial to reiterate it's not a standard python script but a vapoursynth script. (As you can't run python on a script designed to be run inside vapoursynth and expect it to work).

**Comment by myrsloik** [comment]
I'll document it then

**Comment by myrsloik** [comment]
Done
