### ISSUE TITLE
Import EEDI3 improvements

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#325]
The avisynth version of EEDI3 has had quite a bit of optimization applied to it. These changes should probably be imported.

**Comment by HolyWu** [comment]
@myrsloik
Did you already work in progress on it? I ask because I started to port eedi3 using OpenCL 2~3 weeks ago. However at the end only one of the heavy loop could be executed parallelly on GPU, the other heavy loop is still executed on CPU but has SIMD optimized. If you want I could probably write a pure CPU variant as well, but I need to take over the eedi3 namespace then.

**Comment by myrsloik** [comment]
No, didn't touch it at all. Maybe it's better if you use a different namespace if you make big changes.

**Comment by myrsloik** [comment]
eedi3cl now exists (and has cpu optimizations too) so no reason to duplicate the effort
