### ISSUE TITLE
Cross compile error on Mingw

### ISSUE THREAD

**Issue by shinchiro** [vapoursynth/vapoursynth#350]
I've trying to cross compile on mingw. But it seem failed after done compiling `libvapoursynth.a` with following error:
```
x86_64-w64-mingw32-g++: fatal error: cannot specify -o with -c, -S or -E with multiple files
compilation terminated.
make: *** [Makefile:1456: src/vsscript/libvapoursynth_script_la-vsscript.lo] Error 1
```
[build log](http://0x0.st/s80u.log)

**Comment by dubhater** [comment]
Found your problem. It looks like you're passing this in some CFLAGS variable: ``/mnt/c/base/build64/install/mingw/include/python/Python.h``. This is why gcc thinks there are multiple files (this and vsscript.cpp).

 Add ``-I`` at the beginning and remove ``Python.h`` from the end, so that you're passing ``-I/mnt/c/base/build64/install/mingw/include/python/``

**Comment by shinchiro** [comment]
Thanks for the tip
