### ISSUE TITLE
Option to disable blur in sub.TextFile()

### ISSUE THREAD

**Issue by vadosnaprimer** [vapoursynth/vapoursynth#393]
This is probably a problem with all .ass filters. They make fonts look terrible at small sizes. Tested with MPC-HC (internal and VSFilter) and Aegisub, they show this basically the same as vapoursynth:

![test vpy - 27876](https://user-images.githubusercontent.com/7092625/39961515-59114a0c-5640-11e8-8088-c05f6141ef23.png)

Of course soft subtitles look great if you simply zoom in 2x and more. But I'm a part of tasing community that heavily depends on using hard subs (we have to provide necessary info about what those videos are and who the authors are, and we don't want it to get lost if the vids are reuploaded by others). So we have to burn subtitles right into encodes, at whatever size we can afford. And since console footage is mostly 240p and below, we have to either use terribly looking blurred subtitles of sizes that fit in, or use huge subtitle sizes that cover everything in the video.

Text editors and other text based programs (like command prompts) can display fonts in a perfectly pixelated way at any size:
![pnravz3](https://user-images.githubusercontent.com/7092625/39961582-1fd410b0-5642-11e8-8776-c0a15d666c76.png)
![xgd7utv](https://user-images.githubusercontent.com/7092625/39961620-ecf36b22-5642-11e8-954e-4c5fd8c1f43f.png)

If .ass filters were capable of rendering regular fonts with this sharpness, it'd be a life saver for us. In these examples I'm using Lucida Console font and custom fonts that replicate pixel perfect fonts from FCEUX and Gens. But those custom fonts only work well at integer multiples of their internal size, while regular fonts work on any size, so we won't need to hack around.

Therefore I request an option to disable blurring for .ass subtitles. Avisynth obviously suffers from this as well, and I wanted to patch avs+ to handle this, but I was scared to death by its code base, that's why I'm here.

**Comment by HolyWu** [comment]
You probably want to set the outline to 1 or even 0 if the font size is small. I think that's more watchable.

**Comment by vadosnaprimer** [comment]
I disagree, especially about 0.
![test vpy - 27876](https://user-images.githubusercontent.com/7092625/39961515-59114a0c-5640-11e8-8088-c05f6141ef23.png) ![test vpy - 27874 - out1](https://user-images.githubusercontent.com/7092625/39965106-c5a5e122-569b-11e8-85ee-8e037dd0b41f.png) ![test vpy - 27874 - out0](https://user-images.githubusercontent.com/7092625/39965107-c9a7a774-569b-11e8-9317-37c0f4210585.png)

**Comment by dubhater** [comment]
I'm not sure libass has any way to disable antialiasing.

Any chance the text you want to display is super simple *and* you can use an 8x16 px font? If yes, there is [core.text.Text](http://www.vapoursynth.com/doc/functions/text.html). It uses the Terminus bitmap font.

![asdf](https://user-images.githubusercontent.com/1739488/39966695-d2304460-56b8-11e8-8b36-618ffeaa516c.png)


```python
import vapoursynth as vs
core = vs.get_core()


def altText(srcclip=None, msg='', alignment=7): 
    # by jackoneill 2016.08.25 http://forum.doom9.org/showthread.ph...37#post1778537 
    # used by xBox2 etc to replace icore.text.Text 
    icore = vs.get_core()  
    # Print the msg text on a blank clip with the same format as the input src clip. 
    textclip = icore.std.BlankClip(srcclip) 
    textclip = icore.text.Text(textclip, msg, alignment=alignment) 
    # Construct a suitable alpha channel for blending. 
    # Enlarge the text a bit. 
    maskclip = icore.std.Maximum(textclip) 
    maskclip = icore.std.Maximum(maskclip) 
    # text.Text prints in limited range white text (235) on limited range black background (16). 
    # Make them 255 and 0, so the black box doesn't show at all. 
    maskclip = icore.std.Binarize(maskclip) 
    # Blend the text into the input clip. 
    retclip = icore.std.MaskedMerge(srcclip, textclip, maskclip, first_plane=True) 
    return retclip
    
    
src = core.imwri.Read("/tmp/fonts.png")

plain_text = core.text.Text(src, "plain core.text.Text", 5)

fancy_text = altText(src, "fancier core.text.Text", 5)

src = core.std.StackHorizontal([plain_text, fancy_text])

src.set_output()
```

**Comment by CoffeeFlux** [comment]
Somewhat confused what you're asking for here—do you mean you don't want to anti-alias fonts? If you're seeing actual blur, it's the result of your script. Regardless though, this isn't really a vapoursynth issue; all the actual subtitle rendering is handled with libass. The reason every renderer, including libass, anti-aliases is because it's sane behavior, and I suspect no AA in your examples is just going to look worse. I don't think the Lucida example at 12-point even looks that bad, considering the resolution you're working with...

**Comment by CoffeeFlux** [comment]
Oh whoops, I deleted that since I think dubhater's comment was more helpful, but yeah the rendering is all handled in libass itself. And yeah, VS is calling it through ffmpeg iirc. 
I think your best bet is just finding a desired text size and getting a bitmap font that matches though. If you somehow were to turn off AA for one of the vector fonts, it's going to look really bad, way worse than your examples above.

**Comment by vadosnaprimer** [comment]
Windows build steps don't mention ffmpeg or libass. How are they dealt with in an MSVC setup?

Alternatively, does sub.Subtitle() follow the same libass usage logic as sub.TextFile(), or does things internally?

**Comment by CoffeeFlux** [comment]
Believe they're the same, which sadly won't help your issue. No clue about building it on Windows either.

I'm not sure how much flexibility you need in the font height, but there are bitmap fonts that offer a bunch of different sizes. Something like this might work for you: http://terminus-font.sourceforge.net

Sorry I can't be more help :(

**Comment by dubhater** [comment]
The Subtitle plugin uses libass directly, not through ffmpeg. (ffmpeg is used for decoding image subtitles like PGS.)

Windows build steps don't mention ffmpeg or libass because the Subtitle plugin DLLs are compiled separately on a Linux machine.

sub.Subtitle is largely the same thing as sub.TextFile, except it constructs an ASS file in memory from the user's text to pass to libass.
