### ISSUE TITLE
Invalid output of VideoNode.output on exotic resolutions

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#423]
During testing of Yuuno 1.1, my testers reported a completely unrecognizable output when trying to encode clips with exotic resolutions.

Standard resolutions (720p, 1080p, etc.) work fine however.

Code for reproduction:

    c = core.lsmas.LWLibavSource(r"C:\Users\stuxc\Desktop\spyce.mkv")
    m = c.resize.Spline36(width=1516, height=854)[:500]
    with open('lol.y4m', 'wb') as f:
        m.output(f, y4m=True)

The video has then been encoded using the command `x264 --demuxer y4m lol.y4m -o test.mkv`. This is what happens

Windows 10 18.09 x64:
![applicationframehost_2018-11-25_19-39-25](https://user-images.githubusercontent.com/2260352/48983123-4b883a80-f0eb-11e8-8ae6-9319d4be9635.png)

Windows 10 18.03 x64 (different User)
![c7f7da](https://blubb-made.spdns.org/f/c7f7da.png)

Arch Linux:
![k53bc7](https://user-images.githubusercontent.com/2260352/48983128-69ee3600-f0eb-11e8-97e8-23758928aec4.png)

**Comment by Kamekameha** [comment]
Yeah, I'm aware of it. This happens when width != stride (that is, when width is not mod 32) and so its block of memory is technically no contiguous; `io.RawIOBase.write` expects a contiguous buffer.

This was introduced by my `VideoPlane` thing not extensively checking what the flags passed to `VideoPlane.__getbuffer__()` are, this should raise an exception. I've been meaning to fix this since forever but given that nobody seems to use or report anything about these Python APIs I just kinda forgot about it.

**Comment by myrsloik** [comment]
Sigh... you knew you added this bug when changing things around?

**Comment by Kamekameha** [comment]
> At least I try to fix the bugs I make.

Good to know, I did say though that:

> I've been meaning to fix this since forever but given that nobody seems to use or report anything about these Python APIs I just kinda forgot about it.

> But will your fix make this raise an error or just make it a contiguous buffer?

I'll see.

**Comment by stuxcrystal** [comment]
I'd like `VideoNode.output` to be able to output all resolutions. 

So if you decide against it, please revert this https://github.com/vapoursynth/vapoursynth/blob/d6c5e0317d2b3ab8e550773b09069b3904aa17e3/src/cython/vapoursynth.pyx#L494

**Comment by Kamekameha** [comment]
I'd also like that, relax.
