### ISSUE TITLE
zimg could not find LibEventPthreads

### ISSUE THREAD

**Issue by courtens** [vapoursynth/vapoursynth#438]
installing on Ubuntu 19.04 getting: configure: `error: Package requirements (zimg) were not met:`
installing zimg getting `Could NOT find LibEventPthreads (missing: LIBEVENT_PTHREADS_LIBRARY)`
but libevent-dev  `libevent-dev is already the newest version (2.1.8-stable-4build1).`

steps I took: https://askubuntu.com/posts/1130245/edit

Help -- install instructions and needed dependencies are not clear to me... Thank you.

**Comment by 4re** [comment]
You should carefully read Vapoursynth's documentation on how to build it for Linux, the zimg you built is not the one Vapoursynth uses, they are completely different projects. Use https://github.com/sekrit-twc/zimg

Maybe is better if you use the PPA suggested in the documentation instead of building from source.

**Comment by courtens** [comment]
> Maybe is better if you use the PPA suggested in the documentation instead of building from source.
how would I find that? (sorry, new to github maze)

**Comment by courtens** [comment]
OK - got zimg running.

Running `make` in `vapoursynth` brought up a lot for warnings. (see attachment)  Is this normal? 

And how can I check that it is now installed? `vapoursynth -v` gives me `vapoursynth: command not found`

[warnings.html.zip](https://github.com/vapoursynth/vapoursynth/files/3035695/warnings.html.zip)

**Comment by dubhater** [comment]
It's normal. That code uses some deprecated ffmpeg things so that people with older ffmpeg can still compile it.

Try ``vspipe -v``. There is no command called ``vapoursynth``.

This is the PPA where you can find unofficial VapourSynth packages and various things related to it: https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth

**Comment by courtens** [comment]
`vspipe -v` gave me `VapourSynth Video Processing Library
Copyright (c) 2012-2018 Fredrik Mellbin
Core R45
API R3.5
Options: -
`
I must be good to go (right?)

**Comment by dubhater** [comment]
Yes.
