### ISSUE TITLE
VS is very unfriendly for users

### ISSUE THREAD

**Issue by Onemeshnik** [vapoursynth/vapoursynth#448]
I think >95% of users do not have python, but your installer is not standalone, it crashes without Python. It has absolutely different behaviour in 'portable' mode (it's not portable, my player can not launch it).

Mostly vapoursynth developed for devs.

Even SVP has better compact vs libraries. 

I created vs installer which does not need python, it's very simple and small. https://github.com/Onemeshnik/vapoursynth64 . Imho, it could be smaller, I do not know why even SVP has libcrypto

Imho, now vapoursynth is much worse for usability vs avisynth, you just can not push button and install it, it stores parts in different place. I do not want to be too critical, but vs is much less popular (at least if you look in doom9 disscussion, you will see much more disscussion and viewers)

Suggestions:
1. Use simple folder structure (Vapoursynth64\Vapousynth64\plugins can be just Vapousynth64\plugins), if it possible, one scructure for 'portable' and 'regular' mode. For example for using avisynth with potplayer I just place avisynth.dll in potplayer folder and it works. If VS needs so many dependencies, it could be vapoursynth.dll which loads modules from vapoursynth folder.
2. Use internal python, most of software do it and  do not crashes without python.
3. Use as less as possible files. It makes it much easy for understanding
4. Have userfriendly installer, just for 'player can use it'. Most of users are not devs
5. I do not know, but in my case PotPlayer loaded all plugins when I integrated fat pack in system. It freezes for some time because it loaded all plugins in \plugins folder, not \coreplugins and eats more memory even if do not need all modules. May be its glitch
6. If its possible, native compatibility with avisynth syntax and avisynth<->python alliases for variables. As I know, avisynth 'IDE' AVSPmod uses python too
It can looks something like
like
Avisynth{
avisynth code
}
It allows use mostly one code for scripts and migrating from avisynth to vs will be much easier. Also, avisynth syntax is much easy for understanding and uses less letters.

**Comment by stuxcrystal** [comment]
I honestly feel you.
From what I see, you are using Windows. So I will focus on Windows Installs. Here's my take on your issue.

First off, can you please make a PR out of your installer version? Please. I'd love to have this requirement removed from the existing installer.

Now onto your suggestions:

From what you read, you assume that VapourSynth as provided here is primarily inteded to be a plugin for media-players. This is not the case. VapourSynth is primarily intended as a frame-server whose output is to be piped into appropriate video-encoding software. The output of the video-encoding software is the result that is distributed to users (usually after muxing).

However, let's look at your suggestion point for point:

1. Use simple folder structure. If possible, one structure for 'portable' and 'regular' mode. To switch to portable mode, place an empty `portable.vs` file into the same folder as the `vapoursynth.dll`-file that is being loaded. This will cause VapourSynth to look at the plugin-folders in the same directory as the `vapoursynth.dll`-file.
2. Use internal python. This is not the intended use case for most vapoursynth users. If you want to include vapoursynth into a player, *[create your own portable python installation](https://docs.python.org/3.7/extending/embedding.html) and add a portable vapoursynth installation into it (See point 1). Bundle this into your own installer.*
3. I do not understand your suggestion.
4. A) As I see it, the installer is created for the primary use-case of VapourSynth to process videos before distribution. B) See my preface and 2. 
5. I cannot comment on that.
6. I am the developer of an "editor" for VapourSynth scripts. I have considered a lot of ways to implement exactly this feature you're talking about. There are three ways of doing this:
  **a.** Direct interfacing with (single-threaded) AviSynth (multi-threaded or multi-processed with bidirectional communication.) This doesn't work, as the AVS->VS part of the (VS -> AVS -> VS)-flow brings additional concurrency problems. These might be mitigated by implementing #324. The existing "magical" solution spawns a separate process for every bit of AviSynth-code you run through that particular plugin.
  **b.** Emulation of AviSynth-Plugins by implementing the AviSynth-API. [This already exists.](http://www.vapoursynth.com/doc/functions/loadpluginavs.html) To understand why this doesn't work well, you need to know some history about VapourSynth. VapourSynth has been created exactly because *AviSynth was not able to __reliably__ switch to multi-core workloads.* Emulating AviSynth-plugins would import back those concurrency-issues.
  **c.**  Rewriting AviSynth-Code to Python-Code. Doing this is easier than it sounds. But it will either fall back to b. or you need to provide your own implementation for each plugin you use in that vapoursynth-mode.

**Comment by myrsloik** [comment]
Closing as it's a continuation of a low effort troll on D9. @stuxcrystal open a new issue if you have any suggestions.

**Comment by hydra3333** [comment]
I'm not a dev and I like it as it is :)
