### ISSUE TITLE
NASM 2.11.08 fails because of invalid warning flags

### ISSUE THREAD

**Issue by darealshinji** [vapoursynth/vapoursynth#460]
Older NASM versions, 2.11.08 in my case, fail to build because they don't support the flags `-w -Worphan-labels -Wunrecognized-char`. Without those flags it builds fine. Maybe configure should check for a minimum supported version of NASM or test if those flags are supported, for example like this:
```
AS_IF(
    [test "x$NASM" != "x"],
    [
        ac_cv_asm_test_file="config_$(date +"%s%N")"
        rm -f ${ac_cv_asm_test_file}.asm
        touch ${ac_cv_asm_test_file}.asm

        AC_MSG_CHECKING([if nasm supports -w -Worphan-labels])
        AS_IF(
                [$NASM $ASFLAGS -w -Worphan-labels -o ${ac_cv_asm_test_file}.o ${ac_cv_asm_test_file}.asm 2>/dev/null],
                [AC_MSG_RESULT([yes])
                ASFLAGS="$ASFLAGS -w -Worphan-labels"],
                [AC_MSG_RESULT([no])]
                )
        rm -f ${ac_cv_asm_test_file}.o

        AC_MSG_CHECKING([if nasm supports -w -Wunrecognized-char])
        AS_IF(
                [$NASM $ASFLAGS -w -Wunrecognized-char -o ${ac_cv_asm_test_file}.o ${ac_cv_asm_test_file}.asm 2>/dev/null],
                [AC_MSG_RESULT([yes])
                ASFLAGS="$ASFLAGS -w -Wunrecognized-char"],
                [AC_MSG_RESULT([no])]
                )
        rm -f ${ac_cv_asm_test_file}.o ${ac_cv_asm_test_file}.asm
    ]
)
```

**Comment by myrsloik** [comment]
The only bug here is that the build system doesn't check for at least MASM 2.13.x or so.

**Comment by dubhater** [comment]
I propose that those flags are not actually needed, because no one's writing new asm.

A version check would have to be written in (m4)sh and that's too much work...

**Comment by myrsloik** [comment]
I think x264inc.asm is roken with old NASM so don't bother removing them flags.

**Comment by darealshinji** [comment]
You could recommend a minimum version in the build instructions, like you do with Cython.

**Comment by Youka** [comment]
Package **nasm** _v2.13.*_ came with [Ubuntu **bionic**](https://packages.ubuntu.com/bionic/devel/nasm).
**Xenial** uses an [older version](https://packages.ubuntu.com/xenial/devel/nasm) - incompatible with Vapoursynth.

- [Travis just started with bionic](https://docs.travis-ci.com/user/reference/overview/#linux) (which is currently buggy), so most CI users need to build nasm [manually](https://github.com/vapoursynth/vapoursynth/issues/455#issuecomment-513475439).
- [Lubuntu LTS](https://lubuntu.net/downloads/) is still v16.04 (xenial).
- Many companies still operate on _trusty_ or _xenial_.

For the sake of **backwards compatibility** and usability: please try to remove/replace these flags instead of just adding a warning.

**Comment by myrsloik** [comment]
> Package **nasm** _v2.13.*_ came with [Ubuntu **bionic**](https://packages.ubuntu.com/bionic/devel/nasm).
> **Xenial** uses an [older version](https://packages.ubuntu.com/xenial/devel/nasm) - incompatible with Vapoursynth.
So you made an active choice to use an old version? Learn to live with your choices.

> * [Travis just started with bionic](https://docs.travis-ci.com/user/reference/overview/#linux) (which is currently buggy), so most CI users need to build nasm [manually](https://github.com/vapoursynth/vapoursynth/issues/455#issuecomment-513475439).
Explain to me why I care about this? There are plenty of linux distributions. Don't say automated tests because I don't have them.

> * [Lubuntu LTS](https://lubuntu.net/downloads/) is still v16.04 (xenial).
> * Many companies still [operate on _trusty_ or _xenial_](https://ubuntu.com/about/release-cycle).
Oh, so you're interested in a quote for commercial level support with extended compatibility guarantees? Just send me an email with your requirements and I'll get back to you quickly.

> For the sake of **backwards compatibility** and **usability**: please try to remove/replace these flags instead of just adding a warning.
What steps did you take to verify that it actually works? Probably none since x264 (the source of the most complicated asm) requires nasm 2.13. FFmpeg has similar implicit checks that will slay all older versions. I do focus on **usability** by making sure there's no miscompilation.

@Youka You come off as either a company representative trying to make me do exactly your desired task to fit your production flow and damn everyone and everything else. Alternatively you're a clueless person I won't let anywhere near my hobby software projects (as open source for free tends to be) due to the amount of time/fun drain you'd most likely cause. 

Use the fork button if you disagree with this statement.

**Comment by myrsloik** [comment]
Nasm is now no longer needed
