### ISSUE TITLE
Expr produces wrong output

### ISSUE THREAD

**Issue by 4re** [vapoursynth/vapoursynth#500]
```python
import vapoursynth as vs
import finesharp as fs

core = vs.get_core()
core.std.SetMaxCPU("none")  # Commenting this line doesn't change the output

clip

clip = fs.sharpen(clip=clip, use_lut=False)  # This is bugged
# clip = fs.sharpen(clip=clip, use_lut=True)  # This produces the correct output

clip.set_output()
```
https://i.imgur.com/y9Oewrd.jpg

The bug is not present in `47.2` and before.

`use_lut=False` uses `std.Expr` instead of `std.Lut2`.
```python
    if bd in [8, 9, 10] and use_lut is True:
        def expr(x, y):
            d = x - y
            absd = abs(d)
            e0 = ((absd / lstr) ** (1 / pstr)) * sstr
            e1 = d / (absd + 0.001)
            e2 = (d * d) / (d * d + ldmp)
            return clamp(e0 * e1 * e2 + mid, max_)

        diff = core.std.Lut2(clipa=clip, clipb=c2, function=expr)
    else:
        expr = '{x} {y} - abs {lstr} / log 1 {pstr} / * exp ' \
            '{sstr} * {x} {y} - {x} {y} - abs 0.001 + / * {x} {y} - log 2 * exp ' \
            '{x} {y} - log 2 * exp {ldmp} + / * 128 + {scl} *'
        expr = expr.format(x=x, y=y, lstr=lstr, pstr=pstr, sstr=sstr, ldmp=ldmp, scl=scl)
        diff = core.std.Expr(clips=[clip, c2], expr=expr)
```

**Comment by sekrit-twc** [comment]
This looks like an invalid expression. The core expression expands to:

    x 1 / y 1 / - abs 1.49 / log 1 1.272 / * exp 2.0 * x 1 / y 1 / - x 1 / y 1 / - abs 0.001 + / * x 1 / y 1 / - log 2 * exp x 1 / y 1 / - log 2 * exp 2.1 + / * 128 + 1 *

Or after eliminating constants:

    x y - abs N * log M * exp 2 * x y - x y - abs 0.001 + / * x y - log 2 * exp x y - log 2 * exp 2.1 + / * 128 +

Which compiles to the program:

    loadu8       r0,x
    loadu8       r1,y
    sub          r2,r0,r1
    abs          r3,r2
    constant     r4,0.671141
    mul          r5,r3,r4
    log          r6,r5
    constant     r7,0.786164
    mul          r8,r6,r7
    exp          r9,r8
    mul          r10,r2,r9
    log          r11,r2
    add          r12,r11,r11
    exp          r13,r12
    mul          r14,r10,r13
    add          r15,r14,r14
    constant     r16,0.001
    add          r17,r3,r16
    constant     r18,2.1
    add          r19,r13,r18
    mul          r20,r17,r19
    div          r21,r15,r20
    constant     r22,128
    add          r23,r21,r22
    storeu8      r23

Which yields this execution trace:

    [0]	30.0000000	float
    [1]	58.0000000	float
    [2]	-28.0000000	float
    [3]	28.0000000	float
    [4]	0.671140909	float
    [5]	18.7919464	float
    [6]	2.93342829	float
    [7]	0.786163568	float
    [8]	2.30615449	float
    [9]	10.0357580	float
    [10]	-281.001221	float
    [11]	-nan(ind)	float
    [12]	-nan(ind)	float
    [13]	-nan(ind)	float
    [14]	-nan(ind)	float
    [15]	-nan(ind)	float
    [16]	0.00100000005	float
    [17]	28.0009995	float
    [18]	2.09999990	float
    [19]	-nan(ind)	float
    [20]	-nan(ind)	float
    [21]	-nan(ind)	float
    [22]	128.000000	float
    [23]	-nan(ind)	float

NaN was introduced because of expression 11, which is `r11 = log(x - y)`, but `x - y` is negative.

**Comment by myrsloik** [comment]
Did this expression come from an avisynth script originally, and if so, did it work? (link to original also appreciated)

**Comment by sekrit-twc** [comment]
The reason this expression used to evaluate to a finite number (only when using JIT, not under interpreter), is because the numerical approximation of `exp` and `log` used yield a large positive number for `exp(log(x))` and `x < 0`. This is because the `log(x)` approximation returns NaN for `x < 0`, but `exp(x)` returns `e^80*e^0.5` for NaN input. As a result, when evaluated as written, the expression `exp(log(x - y) * 2) / exp(log(x - y) * 2 + 2.1)` evaluates to 1. Under optimization, the numerator and denominator of the exp-log expression was grouped with the first half of the overall expression, which instead yields `(f*BigNum)/(g*BigNum)` instead of `(f/g)*(BigNum/BigNum)`.

The correct way to write this expression is `(x-y)*(x-y)` rather than `exp(log(x - y) * 2)`.

**Comment by 4re** [comment]
Ops... sorry, then this was a mistake on my side. The original expression does not exhibit this behavior.

Thank you for pointing out the mistake.
