### ISSUE TITLE
Create a plugin and script database

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#52]
Make a central place to host and list all plugins and scripts to prevent doom9 treasure hunts. 

Must have features:
List all plugins with a 1-2 sentence description
Have both source and windows binaries
Have maybe 3 additional links (website, doom9 thread, source code place)

Useful:
Allow plugin writers to update their own files

**Comment by MonoS** [comment]
Recently i was thinking about this issue.

A simple site list in which you can upload a file with name, short description [eventually some tags], link to the forum and an optional html page with a more complete description [this page will be hosted on the server].

The main page will be a list of all plugin and script with a searchbox on the top that make a search as-you-type in name, short description [and eventually tags].

What do you think??

**Comment by myrsloik** [comment]
I guess it's a start. Actually I like the rst style documentation so I think that'd be the best to allow to be uploaded.
The other main thing I want is a proper database with namespace and function names registered because I want to make a simple plugin manager for windows. Would be very convenient if all plugins and ready made scripts could be automatically downloaded and installed by a manager.

**Comment by torque** [comment]
As someone who doesn't matter at all, allow me to butt in.

Might I suggest doing something a bit more modern than a monolithic site for packages? I think that it would make a lot more sense to have a git repository for a list of packages. There are a number of package managers (e.g. [Homebrew](https://github.com/Homebrew/homebrew), [Alcatraz](https://github.com/supermarin/alcatraz-packages), [Package Control](https://github.com/wbond/package_control_channel), and [Funtoo Linux](https://github.com/funtoo/funtoo-overlay)) that have git-backed indexes on github, and it seems to work pretty well. It offers an easy-to-use interface that the majority of developers will be familiar with right out of the box.

This doesn't necessarily cover hosting of binaries the way a website would, but it doesn't preclude it, either. For example, the homebrew project has pre-built binaries for many of their source packages that are served from sourceforge. Github itself could be abused into hosting binaries, I expect.

And then if you want a website, all you need to do is fetch a JSON list of available packages, and turn it into something pretty. It wouldn't even necessitate a dynamic backend, and a client bundled with vapoursynth could use the exact same index.

It cuts down the work from building an entire site to simply designing an appropriate package list schema.

**Comment by myrsloik** [comment]
The problem is that they all consume packages in different formats. After that I'd have to write something that adapts the magic list for each and every package system. There are too many. If there were only three systems or less I'd consider it. A website is also a must because I want users to be able to easily browse existing plugins which a package manager doesn't.

**Comment by wm4** [comment]
>The problem is that they all consume packages in different formats. After that I'd have to write something that adapts the magic list for each and every package system. There are too many. 

Without having read everything torque wrote, I think his point is to steal an existing package management system and to use that, instead of writing your own software. You just have to pick one...

**Comment by myrsloik** [comment]
Name one that works everywhere and I'll use it.

**Comment by torque** [comment]
I wasn't suggesting that you create packages for those package managers but merely listing them as examples of successful git-backed plug-in managers/lists.

What I was actually suggesting was that you create some simple JSON schema for describing a package adequately, and then create a repository to host user-submitted schema. People who want to add packages to the official listing can simply submit a pull request to the package list repository. Obviously the schema does not have to be JSON, but it is the most reasonable object notation in my opinion.

For example, the Package Control package schema looks something like:

```JSON
{
	"name": "Package Name",
	"details": "https://github.com/fake user/fake repository",
	"labels": ["useless", "metadata"],
	"releases": [
		{
			"sublime_text": "*",
			"platforms": ["osx", "linux"],
			"tags": true
		}
	]
}
```

This could be made more/less complicated as deemed necessary. [npm also uses JSON schema to describe packages](https://docs.npmjs.com/files/package.json), but it is fair amount more complicated due to including dependency management.

The overall point: I think it would be better to have an open listing rather than a mysql database hidden away on some server. Arguments that I am wrong and/or dumb are welcome.

**Comment by splinter98** [comment]
Personally I'm not sold on the 'Pull request' Github method being the backbone of the package manager.

If the number of plugins gets large it will become a really inefficient to search and maintain. (For example Alcatraz you linked above has a single file covering all the plugins in the system) Also plugin maintainers will have to wait for pull requests to get accepted when they update their plugins. Git isn't really designed for granting access on limited subset of a repo which would in my opinion be required otherwise you need to rely on package maintainers to action on every minor update of a plugin.

I would agree we should have some nice JSON or YAML like REST API to talk to whatever system we have, that way different tools can be created to download and install plugins when they're required. (Command line interface, IDE integration to name a few).

I do agree on your overall point that we have an open listing, with the whole package management codebase being open source, with easy way to mirror the database. Although security should be taken into serious consideration! IF we had public mirrors we would need to implement some way of ensuring that the plugin they just downloaded, is actually the library they wanted and not some malicious binary that can hack into the system. (The more I think about this whole idea the less trivial it becomes and I can appreciate why there are whole teams of people dedicating time and energy into this problem)

**Comment by torque** [comment]
>IF we had public mirrors we would need to implement some way of ensuring that the plugin they just downloaded, is actually the library they wanted and not some malicious binary that can hack into the system. (The more I think about this whole idea the less trivial it becomes and I can appreciate why there are whole teams of people dedicating time and energy into this problem)

In my opinion, the git repository solves this problem. It allows all packages to easily be audited by any team members with access rather than by the one person who controls the website, and anybody can review a pull request before it has been merged. If you're going to have a centralized, officially endorsed package listing, you should really be checking all incoming packages anyway. Allowing the natural workflow of git/github to work for you in this regard seems like a good idea to me.

In terms of your claims of maintenance scaling troubles, I doubt it'd be a problem. I personally don't expect the number of plugins to skyrocket, as this is kind of a niche project (there aren't really that many people who care about script-based video editing, and most of those who do are still happy with Avisynth). As for storing everything in one file, it would be easy to have a folder hierarchy where every project gets its own file, and have a TravisCI (or similar) job concatenate all of the projects into a single listing on commit.

At the end of the day, I guess you just have to have some trust that plugin developers aren't putting rootkits and backdoors in their code.

Anyway, I guess I've mostly said my piece, so I'll let this issue run its course without any more bikeshedding on my part.

**Comment by magicgoose** [comment]
> Github itself could be abused into hosting binaries, I expect.

It's not necessarily _abuse,_ Github's _releases_ are even meant to be used like this, at least that's what became commonly accepted practice. See for example https://github.com/sqlitebrowser/sqlitebrowser/releases
And also there's a new feature "Large FIle Storage"

**Comment by magicgoose** [comment]
Speaking for the issue, I suggest something like this:
Plugin authors host the code in some git repositories (or maybe mercurial, but idk why anyone would want something other than git), and the plugins' repositories contain some "special" metadata-file among other files, which describes various requirements, dependencies, build procedure for all supported platforms, etc for this plugin.
VS keeps track of the existing repositories and automatically scans them, and displays all information derived from these "metadata"-files. This way there'll be no extra manual work to do on VS side, except simply adding links for known plugins. Once added, they'll automatically update themselves in the database when the author updates the code.

And also I think it doesn't have to be a full-blown backend, a periodically (auto-)updated [Github page](https://pages.github.com/) will probably be fine. (a script watches for updates in plugin repos and when there are any, commits metadata update to the github page's repository)

**Comment by myrsloik** [comment]
I think I'll go with magicgoose's last comment suggestion. It should be fairly quick to implement and I've already started doodling on the json shit.

**Comment by theChaosCoder** [comment]
Are there any updates on this?

@magicgoose I looked at the github api and for most plugins you can just use the releases (meta)data to check for updates. So no special meta data would be needed. It is a bit harder for vs scripts, but it's possible to check for new commits / last update ...


I think it would be nice to include relevant functions with a short description which especially is useful for big scripts like havsfunc.

```
   "tdeintmod":{  
      "namespace":"tdm",
      "author":"HolyWu",
      "type":"plugin",
      "description":"TDeintMod is a combination of TDeint and TMM, which are both ported from tritical's AviSynth plugin http://bengal.missouri.edu/~kes25c/.",
      "version":"r8",
      "gitrepo":"https://github.com/HomeOfVapourSynthEvolution/VapourSynth-TDeintMod",
      "doom9":"https://forum.doom9.org/showthread.php?t=171295",
      "gpu-support":false,
      "functions":[  
         "TDeintMod",
         "IsCombed"
      ],
   },
```

```
some script:
      "functions":[ 
         "crossfade":{  
            "description":"Crossfade clipa into clipb. Duration is the length of the blending zone."
         },
         "retinex_edgemask":{  
            "description":"Use retinex to greatly improve the accuracy of the edge detection in dark scenes."
         },
       ...
      ],
```
Or maybe some usefull tagging is enough like masking stuff, sharpening stuff etc.
But I agree that the "special metadata-file" would be a nice(r) way.

**Comment by myrsloik** [comment]
@theChaosCoder 
No updates at all. I simply didn't feel inspired and working on the actual project definitely is more exciting. Your example looks ok but the main draw would be to list dependencies too for both plugins and scripts. That way you'd automatically get everything just by doing "install qtgmc" for example.

I wish I could simply borrow a system from somewhere...

**Comment by dubhater** [comment]
https://aur.archlinux.org/packages/?O=50&K=vapoursynth
https://aur.archlinux.org/packages/vapoursynth-plugin-havsfunc/

*ducks*

**Comment by myrsloik** [comment]
I know that fairly good package collections exist. That's nice. Problem is that you can't use the arch linux packages on windows... so a solution is needed there. And every other linux distro.

**Comment by theChaosCoder** [comment]
I think I will start to make a big monolithic json file on github with all relevant information  + github page with js search and filter stuff. I will post this on the doom9 forum if I have some basic stuff working. Maybe some members will help with the meta data hunt.


Btw. Lets say one would want to pack some stuff for a windows package manager (chocolaty.org) then plugins could go in <AppData>\VapourSynth\plugins64 but what about scripts? Is there an auto load functionallity for scrips as well?

**Comment by myrsloik** [comment]
I think python may have a per user dir for it but not sure. You'll have to consult the python docs for that...

**Comment by theChaosCoder** [comment]
I'm about to finish my first version of a plugin & script database. I also included the default parameter for python functions, but I'm looking for a way to do this for plugins.

for scripts **inspect.signature()** works vey good. Is there any way to do this for a plugin dll, can't anything useful for that?

**Comment by myrsloik** [comment]
No, the defaults aren't exported anywhere. The defaults also depend on input format and other arguments in several cases. Even something simple like the AddBorders filter has this kind of dependency which is why the color argument is specified as the human readable <black> and not the full conditions.
Are the defaults really that important?

**Comment by theChaosCoder** [comment]
No, not that important. I just like the idea to quickly lookup parameters for X filters in a single place.
One other reason would be to provide this info for tools like vseditor.

**Comment by myrsloik** [comment]
When will there be a technical alpha to try? I'm curious about your creation.

**Comment by theChaosCoder** [comment]
Maybe tomorrow.

**Comment by theChaosCoder** [comment]
Here's a pre-alpha. It contains only scripts and no plugins, but you get the idea. 
A version string for each plugin will be added automatically later (script almost ready). No author bcs I don't know which nick, doom9 username, real or fake name to write down.

Just open the html in your browser: [vsdb_prealpha.zip](https://github.com/vapoursynth/vapoursynth/files/1817200/vsdb_prealpha.zip)

**Comment by detuur** [comment]
At the risk of bikeshedding, [TOML](https://github.com/toml-lang/toml) is a much more convenient and readable format for these sorts of package descriptor files, which is why projects such as Rust make use of it ([example](https://github.com/ogham/exa/blob/master/Cargo.toml)). The syntax is more Pythony which just fits Vapoursynth a bit better as well. Just my $0.02.

**Comment by myrsloik** [comment]
https://github.com/vapoursynth/vsrepo

It is done
