### ISSUE TITLE
Support for slice assignment

### ISSUE THREAD

**Issue by po5** [vapoursynth/vapoursynth#529]
Slice assignment would make it easier to manipulate part of a clip.

This example displays a logo for frames 20-150:
```py
v = core.ffms2.Source('video.mkv')

logo, logo_mask = core.imwri.Read('logo.png', alpha=True)
logo = core.resize.Point(logo, v.width, v.height, format=v.format, matrix_s='709')

with_logo = core.std.MaskedMerge(v[20:151], logo, logo_mask)

v[20:150] = with_logo
```
which currently raises an exception `TypeError: 'vapoursynth.VideoNode' object does not support item assignment`
The way to achieve this currently isn't very pretty.
```py
v = v[:20] + with_logo + v[151:]
```
It would be nice to have access to this python feature.

**Comment by myrsloik** [comment]
That makes sense. I'll definitely do it but it might take a while.

**Comment by stuxcrystal** [comment]
I'd love to have this syntax. However, I don't think you can implement that.

Consider this example:

```py
from vapoursynth import core
v = core.ffms2.Source('video.mkv')
w = v
def animator(n):
   if n > 255:
      return w
   else:
      return v

y = core.std.FrameEval(v, animator)
```

In this example it is easy to see, that `y` will be the same as `v` and `w`.

Let's imagine that item-assignment has been implemented.

```py
from vapoursynth import core
src = core.ffms2.Source('video.mkv')
v = src
w = v
def animator(n):
   if n > 255:
      return w
   else:
      return v

v[100:500] = v.std.Invert()
y = core.std.FrameEval(v, animator)
```

You might expect the resulting clip look like this:
Frame 0-99: src
Frame 100-255: src inverted
Frame 255-end: src

This is, in fact, not the case. The actual resulting clip is:
Frame 0-99: src
Frame 100-499: src inverted
Frame 500-end: src

Why? In Python everything you do is operating on references. When assigning one variable to another, you just copy the reference, not the actual object. Calls are always by reference. Yes, even ints and similar basic data-types.

Therefore, in the example above `v`, `w`, and `src` are the identical object. 

The second thing you need to know: Item-Assignments in Python do not reassign to the variable. Instead, they are equivalent to function calls on the variable: The code `x[k] = v` is internally executing `x.__setitem__(k, v)`. `x` is not reassigned.
Slice assignments are just a fancy way to do item-assignment and in fact, do the same: `x[a:b:c] = v` is equivalent to `x[slice(a,b,c)] = v` which is the same as `x.__setitem__(slice(a,b,c), v)`. `x` is not reassigned, too.

Thus, the `v[100:500] = v.std.Invert()`-syntax would need to modify the internal state of `v` to achieve the desired effect. Since `v`, `w` and `src` are the identical object, this also changes `w` and `src`.

Thus to make the example above work, we'd need to implement a copy-operation that duplicates the internal state of a `VideoNode` object.

```py
from vapoursynth import core
src = core.ffms2.Source('video.mkv')
v = src.copy()
w = v.copy()
def animator(n):
   if n > 255:
      return w
   else:
      return v

v[100:500] = v.std.Invert()
y = core.std.FrameEval(v, animator)
```

This did not matter before, as you couldn't change a `VideoNode` instance and therefore it didn't matter if you'd copy the node or just copy a reference to the node.

This guarantee of immutability, is in my opinion a fundamental guarantee of the VapourSynth-Wrapper and can't be broken without fundamentally breaking potentially every library and possibly script as now the clip may now be changed between calls to FrameEval or similar callbacks.

**Comment by myrsloik** [comment]
That's a really good reason not to do it. I guess it won't happen then...
