### ISSUE TITLE
Resizer.html filter crashes computer on encoding

### ISSUE THREAD

**Issue by shanalogic** [vapoursynth/vapoursynth#558]
Ugh I'm hoping someone can help me with this mysterious issue. 

**Whenever I use the KNLM filter in the resizer.html and set up my editor file to encode, it crashes my entire computer instantly.** Every other filter on the resizer.html seems to work just fine - it's just the KNLM filter that crashes everything (which is sad because I love it the most)

The weird thing is that it was working fine the first few times I used it, so I know it was set up properly. Then about a day later it started crashing, but would work after a few tries. Now it instantly crashes without even trying.

I use an iMac, Mojave, 10.14.6

I am not a coder and understand very little code unfortunately (mostly I just paste the resizer code in and add a # to one line :P   I'm wondering if there's some hidden cache or something messing something up?

I'm hoping you guys can help though!

<img width="1359" alt="Screen Shot 2020-04-15 at 6 22 04 PM" src="https://user-images.githubusercontent.com/31083687/79394710-24cbdd80-7f46-11ea-9e9e-34b49b05b69b.png">
<img width="848" alt="Screen Shot 2020-04-15 at 6 21 48 PM" src="https://user-images.githubusercontent.com/31083687/79394726-2ac1be80-7f46-11ea-8560-8989a3d56408.png">
<img width="879" alt="Screen Shot 2020-04-15 at 6 22 45 PM" src="https://user-images.githubusercontent.com/31083687/79394729-2dbcaf00-7f46-11ea-9f97-1e44c59f5ed5.png">

**Comment by shanalogic** [comment]
Update: I updated my os x to Catalina and noticed that the encoder ran one line of code before crashing my computer instead of crashing immediately??

**Comment by Kiyamou** [comment]
At first, it's a problem about KNLMeansCL. So checking the [original repo](https://github.com/Khanattila/KNLMeansCL) may be easier to get help.

The function `knlm.KNLMeansCL()` has a parameter `device_type`, which is to select OpenCL device \(CPU or GPU\). Maybe you can try different modes. More infomation: https://github.com/Khanattila/KNLMeansCL/wiki/Filter-description#OpenCL.

Besides, because KNLMeansCL need OpenCL, please check your graphics driver.

If above methods don't work, [TNLMeans](https://github.com/VFR-maniac/VapourSynth-TNLMeans) may be an alternative.

**Comment by Kiyamou** [comment]
Have you solved this problem?
If not, you can test other filters which use OpenCL, such as [`tcanny.TCannyCL`](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-TCanny). To check your GPU is right or not.

On the other hand, maybe you need adjust the paramter `device_id` in KNLMeansCL. You can get the device's id like this.
```pythob
core.tcanny.TCannyCL(src, list_device=True)
```

**Comment by myrsloik** [comment]
Abandoned issue
