### ISSUE TITLE
SetFrameProp Consider moving to a dictionary as argument

### ISSUE THREAD

**Issue by rlaPHOENiX** [vapoursynth/vapoursynth#559]
SetFrameProp is super annoying to add multiple props.

Perhaps accept a zero-indexed list:

    core.std.SetFrameProps(clip, props=["foo", "bizz"], values=["bar", "bazz"])

or a key-value dictionary:

    core.std.SetFrameProps(clip, props={"foo": "bar", "bizz": "bazz"})

it would make much more sense than having to resort to the following (when under lambda constraints):

    core.std.SetFrameProp(core.std.SetFrameProp(clip, prop="bizz", data="bazz"), prop="foo", data="bar")

**Comment by myrsloik** [comment]
Makes sense

**Comment by sekrit-twc** [comment]
The problem is the type model used in VS functions. Since different props can be different types, but VS only allows an array argument to be of one type, the proposed function signatures would need to be special-cased.

One thing that would work is this:
    std.SetFrameProps(clip clip, string[] strprops, string[] intprops, string[] floatprops, string[] strvalues, int[] intvalues, float[] floatvalues)

**Comment by rlaPHOENiX** [comment]
Or just do a type() check on each value item of the dictionary instead

**Comment by myrsloik** [comment]
Or some special case cython stuff to wrap it. It's a least a bit awkward now so maybe I'll try some solution later.

**Comment by stuxcrystal** [comment]
Can we just allow to put VSMaps into VSMaps?

Other plugins might benefit from something like that too.

**Comment by Kamekameha** [comment]
Something like this could work, too, https://gist.github.com/Kamekameha/52a0bf445c637437f74350ec88df468f.

Many things may look out of place because it's made to work with my local fork of the project, but modifications should be somewhat easy to do.  The rest is just shitty C-looking Cython code.

Skipping both vapoursynth's plugin and type system (well, not entirely in this case as I translate a Python `dict` to a `VSMap`) allows us to not restrict functions to the kind of function signatures of vapoursynth and expose them to Python directly instead.

The name of the function being `update()` is so because I see the operation as analogous to updating a `dict` with `dict.update()`.  It could be named anything, though.

**Comment by myrsloik** [comment]
Here's one change I've been thinking about:
Allow functions to specify they accept anything (just like in V4 the return type can be "any") and let it sort things out itself by examining the VSMap. That would allow this to be efficiently implemented but with only one notable quirk remaining:
How to pass the clip it applies to and separate it from the other values that should be set. Do we simply make an assumption that clip (or another more obscurely named key) can't be set this way.

Have a good answer for that one and then we can have:
SetFrameProps({ clip:clip, '_Matrix': 1, '_Transfer': 4 })
RemoveFrameProps(clip, keys=<list of key names to remove if they exist>)

This would skip the whole VSMap in VSMap complexity.

**Comment by myrsloik** [comment]
Idea in previous post implemented. Seems to work surprisingly well. Don't name frame properties "clip" and you're all good.
