### ISSUE TITLE
Creating empty VideoNode() crashes VS

### ISSUE THREAD

**Issue by Zumochi** [vapoursynth/vapoursynth#561]
The VapourSynth documentation suggests using a simple addition operator to splice clips together.

Splicing one-by-one when you have dozens or hundreds of clips is not feasible, so doing this in a loop seems fairly logical.

However, you need a variable to start with.

- Using `None` doesn't work: `TypeError: unsupported operand type(s) for +: 'NoneType' and 'vapoursynth.VideoNode'`
- Using an empty `VideoNode()` object crashes VapourSynth entirely without any stack trace:
   ```
   (VapourSynth) E:\me\Videos\Encoding> ipython
   Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
   Type 'copyright', 'credits' or 'license' for more information
   IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.
   
   In [1]: import vapoursynth as vs
   
   In [2]: vs.VideoNode()
   (VapourSynth) E:\me\Videos\Encoding>
   ```

I managed a simple workaround of the issue:

```python
video = None
for s in sources:
    if video is None:
        video = s
        continue
    video = video + s
```

...but it seems to me that the crash is something that should be fixed :)

**Comment by Lypheo** [comment]
You can just use ``core.std.Splice(sources)``

**Comment by myrsloik** [comment]
Oh, you found a bug. It should reject the class call instead of crashing. For some reason the code to do that isn't triggered here unlike in other classes.

**Comment by Kamekameha** [comment]
That's because raising an exception at the `__init__()` phase should _not_ be how instantiation is forbidden, but rather by leaving the type's `PyTypeObject.tp_new` member empty.  Currently, there's no "cythonic" way of doing this.

What's happening here is that by the time `__init__()` is called the object has already been created, although in an unusable state.  Raising an exception in there in most cases causes the object to go out of scope, which in turn calls the respective `PyTypeObject.tp_dealloc` member function (or `__dealloc__()`, in Cython space).  At this point, accessing `VideoNode.funcs` is bound to fail.

https://github.com/vapoursynth/vapoursynth/blob/3d92677bbac1daa1f1ad6f28998369d2626b859f/src/cython/vapoursynth.pyx#L1213-L1214

One relatively easy fix would be making the `VSAPI` pointer a global, which would also just so slightly reduce another discrepancy between vsscript and normal execution.  The proper fix, though, would be as I mentioned, leaving `tp_new` empty.

**Comment by myrsloik** [comment]
Are fields set to null that early in the initialization process? Because if so it can be worked around with a null check here and there in __dealloc__ and just be horrible.

**Comment by Kamekameha** [comment]
Yes, Python's memory allocator for objects memsets the memory to null.

**Comment by myrsloik** [comment]
Fix committed so now you'll simply get an exception when doing naughty stuff. Will post a test build in a few days.

**Comment by Zumochi** [comment]
Thanks! For reference: fixed in b5deeb103e14b0ebd6920917c9336b33f5c3157d. Please do correct me if I got the wrong commit :)

@Lypheo can you elaborate on how that would work around the issue described here? You will still start the first iteration of the loop with an empty clip.

**Comment by DJATOM** [comment]
Declare list for clips
`clips = []`
and append your vids 
`clips.append(video)`
and then concatenate into clip with 
`core.std.Splice(clips)`

**Comment by myrsloik** [comment]
I guess this is resolved since a fix for the crash is in R50 and a good code pattern has been posted by @DJATOM
