### ISSUE TITLE
zimg assigns wrong prop when converting subsampled YUV -> GRAY

### ISSUE THREAD

**Issue by kgrabs** [vapoursynth/vapoursynth#577]
zimg assigns the wrong _ChromaLocation prop when converting from subsampled YUV to GRAY. I tested it with YUV420P8/16/S and zimg changes it from 0 to 1, whereas using ShufflePlanes keeps the correct prop.

Comparison made using the script below
https://slow.pics/c/EgfMcEI2

```
# to 4:2:0
src = core.imwri.Read(r'C:\TextTest_4k.png')
src = core.resize.Spline36(src, format=vs.YUV420P8, matrix=1).std.CropAbs(width=480, height=136)

#Convert to GRAY8 and shuffle chroma back in

#ShufflePlanes
clipa = core.std.ShufflePlanes(src, 0, vs.GRAY)
clipa = core.std.ShufflePlanes([clipa, src], [0,1,2], vs.YUV)
#zimg 
clipb = core.resize.Point(src, format=vs.GRAY8)
clipb = core.std.ShufflePlanes([clipb, src], [0,1,2], vs.YUV)

#Labeling 
a = src.text.Text('Source', 7)
b = clipa.text.Text('YUV420P8 -> GRAY8 (shuffleplanes)', 7)
c = clipb.text.Text('YUV420P8 -> GRAY8 (zimg)', 7)

#Display frame props and zoom in with nearest neighbor
out = (a+b+c).text.FrameProps(alignment=9).resize.Spline36(format=vs.RGB24, matrix_in=1)
core.resize.Point(out, out.width << 2, out.height << 2).set_output()
```

Test image:
![TextTest_4k](https://user-images.githubusercontent.com/29096468/83044768-a2d5d680-a012-11ea-96df-e46e32fdf13e.png)

**Comment by sekrit-twc** [comment]
GRAY clips don't have a chroma location...

**Comment by Frechdachs** [comment]
The following behaviour is strange, too:

```python
clipa = core.std.BlankClip(format=vs.YUV420P8)
clipa = core.resize.Spline36(clipa, format=vs.YUV444P16).text.FrameProps()
# clipa has _ChromaLocation 0

clipb = core.std.BlankClip(format=vs.RGB24)
clipb = core.resize.Spline36(clipb, format=vs.YUV444P16, matrix_s="709").text.FrameProps()
# clipb has _ChromaLocation 1
```

In my opinion, the default should be `left` (0), when converting from non-YUV to YUV, unless otherwise specified.

**Comment by Frechdachs** [comment]
@sekrit-twc Yes, but why is it set to `1`? This causes problems when you want to merge your Y plane back with the original chroma planes.

**Comment by sekrit-twc** [comment]
The current behavior is to set chroma_location to CENTER for clips without subsampling. `clipa` in the example has a "bug," because the chroma location is copied from the input without considering the subsampling change. The normalization of chroma location was introduced to assist in checking if the source and target formats are the same, so that GRAY->LEFT to GRAY->CENTER does not require a useless resampling operation. We could propagate chroma location to RGB, 4:4:4, and GRAY clips, but it needs some thought to ensure there are no other side effects.

**Comment by Frechdachs** [comment]
That makes sense, though, wouldn't setting chroma_location to `0` for clips without subsampling be a better idea, so that it matches the default of subsampled clips. This would cause less problems, because almost anything is left aligned nowadays and if you work with different chroma locations, you have to be extra careful anyways.

**Comment by sekrit-twc** [comment]
We can separate the discussion into individual questions:

1. What is the value of _ChromaLocation when converting from a subsampled to an unsubsampled format with `resize`?

2. What is the value of _ChromaLocation when converting from an unsubsampled to a subsampled format with `resize`?

3. What is the resulting _ChromaLocation when using `std.ShufflePlanes` to combine GRAY clips?

Currently, the way it is intended to work, (1) sets CENTER, (2) sets LEFT, and (3) copies the value from the Y plane. As a result of a logic error, (1) and (2) sometimes use the input value instead.

Let us look at some other approaches:

1a. Delete _ChromaLocation when converting to unsubsampled

1b. Copy _ChromaLocation when converting to unsubsampled

1c. Normalize _ChromaLocation to CENTER (current intended)

So far so good. None of these have any semantic differences.

2a. Unless otherwise requested, use LEFT when converting to subsampled (current intended)

2b. Use _ChromaLocation from the unsubsampled clip to decide the subsampled chroma siting

This is where the semantic questions begin to arise. If someone has a RGB clip with _ChromaLocation equal to BOTTOM_LEFT, what does that mean for the 4:2:0 result?

3a. Copy from the clip providing the luma plane (current)

3b. Delete _ChromaLocation after shuffling

3c.. Copy from the clip providing the chroma plane, but only if the plane was originally a chroma plane.

If we implement (1b) and (2b), then (a) would retain the original _ChromaLocation when we recycle the luma plane into another clip, but what if the chroma planes are coming from a clip with a different subsampling? Chroma siting is a property of the chroma plane, not the luma plane. The indecisive solution would be (b), which would be equivalent to resetting _ChromaLocation to LEFT. (c) would work for more cases, but what if the chroma plane had already been extracted into a luma plane? The most problematic of the decisions is the matter of `std.ShufflePlanes`. Since it takes planes and changes their type, the interpretation of luma or chroma-specific properties is not well-defined.

**Comment by sekrit-twc** [comment]
Implemented 1a+2a+3a
