### ISSUE TITLE
vspipe and clip.set_output()

### ISSUE THREAD

**Issue by jheins3** [vapoursynth/vapoursynth#631]
I am new to Vapoursynth. Can you tell me why you should use these two components in a vs script? 

Why not use subprocess.pipe() to output to FFMPEG (or whatever). 

What does clip.set_output() do? 

I am asking because I am wondering if say in 
pseudocode: 

```
clip = "my_loaded_video.avi"
clip = haf.QTGMC(clip)

subprocess.pipe("clip | ffmpeg to file")
```

-or-

```
clip = "my_loaded_video.avi"
clip = haf.QTGMC(clip)
clip.set_output()

subprocess.pipe("clip | ffmpeg to file")
```

-or-

```
clip = "my_loaded_video.avi"
clip = haf.QTGMC(clip)
clip.set_output()

subprocess.Popen(vspipe, "clip | ffmpeg to file")
```

is valid?

**Comment by OrangeChannel** [comment]
First, I assume you mean a more complex subprocess call with `subprocess.pipe` as that's not an actual function in the subprocess module. And second, you can't simply pipe the `clip` object in the first example from the Python script unless you somehow get a useable version of the clip object to stdout (which you can do but that comes later).

[`.set_output(index)`](http://vapoursynth.com/doc/pythonreference.html?highlight=pipe#VideoNode.set_output) makes it so the clip at `index` can be retrieved from a script using the C API (or `vapoursynth.get_outputs()`), and [`.output()`](http://vapoursynth.com/doc/pythonreference.html?highlight=pipe#VideoNode.set_output) is the method that allows for piping within the Python script.

There's currently an issue with `.output()` and piping, and it's been fixed in the doodle1 branch (related issue https://github.com/vapoursynth/vapoursynth/issues/608), *but* if you want to do something with piping from within the script directly to FFmpeg or something similar, you could with the following:

```py
...
import subprocess
def encode(clip: vs.VideoNode, filename: str) -> None:
    ffmpeg_args = ['ffmpeg', '-i', 'pipe:', filename]
    enc_proc = subprocess.Popen(ffmpeg_args, stdin=subprocess.PIPE)
    clip.output(enc_proc.stdin, y4m=bool(clip.format.color_family == vs.YUV))
    enc_proc.communicate()


>>> clip = core.ffms2.Source("my_loaded_video.avi")
>>> clip = ...
>>> encode(clip, 'out.mp4')
```

`.set_output()` on the other hand makes it easy to encode using [vspipe](http://vapoursynth.com/doc/vspipe.html#examples).

`.set_output(index)` has more uses if using a previewer that supports grabbing multiple nodes from `.get_outputs()` or you're developing something like that, but not if you're just encoding normally.

There's much more in-depth methods of rendering frames, and projects like https://github.com/Endilll/vapoursynth-preview currently use them to get frames rendered as Qt images but that's probably not what you're looking for.

**Comment by myrsloik** [comment]
Your pipe example reveals another reason. You can't seek in pipes and that's a quite useful property too.
