### ISSUE TITLE
_ChromaLocation not passing to the encoder?

### ISSUE THREAD

**Issue by rlaphoenix** [vapoursynth/vapoursynth#647]
When I load my video using D2V, since it's mostly progressive d2vsource loads it with a ChromaLocation of 0 (left), however, it seems this video was originally encoded with a ChromaLocation of 2 as it noticeably fixes chroma bleed by setting a ChromaLocation of 2.

Comparison of 0 vs 2: https://slow.pics/c/mC9cIvVY

I'm doing this via `core.resize.Point(clip, chromaloc_in=0, chromaloc=2)`.

I'm encoding with FFmpeg -c libx264 (so basically x264) and when I set -x264opts chromaloc=2 and encode, the result is identical to any other x264opts chromaloc value. If I leave out that -x264opts entirely, it still never makes a difference.

The only thing I can see the result of the ChromaLocation change is in VapourSynth Editor's Preview window. Perhaps I'm misunderstanding something?

**Comment by myrsloik** [comment]
I don't know how much various h264 decoders actually respect the chroma location. That could be the reason you don't see it anywhere else.

**Comment by rlaPHOENiX** [comment]
If that's the case, is there a way to set up the clip so that it is as if the source is ChromaLocation of 0 (left), so that when encoded, it should act like normal? Thats essentially my goal, to fix the ChromaLocation of 2 (which loads in as 0) to 0 (left) after using d2vsource, so when encoded, the player can position it correctly (assuming it will use chroma location 0).

**Comment by sekrit-twc** [comment]
Belatedly, the solution is:

````
clip = core.std.SetFrameProp(clip, '_ChromaLocation', assumed_source_chromaloc)
clip = core.resize.Bicubic(clip, chromaloc=desired_chromaloc) # Can not be point. Point can not apply subpixel shifts.
````
