### ISSUE TITLE
Drop Windows 7/Windows Server 2008 R2 support?

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#677]
Because Python 3.9 no longer support Windows 7/Windows Server 2008 R2.

https://www.python.org/downloads/release/python-390/

Is there python 3.8's Vapoursynth R53 Build? 

Or Vapoursynth choose to drop Windows 7/Windows Server 2008 R2 support?

**Comment by myrsloik** [comment]
> Is there python 3.8's Vapoursynth R53 Build?

It's called R52 at the moment.

> Or Vapoursynth choose to drop Windows 7/Windows Server 2008 R2 support?

It's dropped. I don't even have hardware that can run it anymore and MS dropped support as well. You can still compile you own Python 3.8 version if you really want it. Simply revert the single commit that bumped the python version details.

**Comment by fuchanghao** [comment]
> > Is there python 3.8's Vapoursynth R53 Build?
> 
> It's called R52 at the moment.
> 
> > Or Vapoursynth choose to drop Windows 7/Windows Server 2008 R2 support?
> 
> It's dropped. I don't even have hardware that can run it anymore and MS dropped support as well. You can still compile you own Python 3.8 version if you really want it. Simply revert the single commit that bumped the python version details.

1.First Windows 7 Still have ESU till Jan. 2023, If use Windows Embedded PosReady 7's patch can stayed to Oct. 2024.

https://docs.microsoft.com/en-us/lifecycle/products/windows-7
https://docs.microsoft.com/en-us/lifecycle/products/windows-embedded-posready-7


Second, I have tested Windows 7 by i5 9400kf CPU and SN550 nVME SSD, But Microsoft's official nVME driver should be installed to the install image first and the OS should be installed by windows 10 install media or 3rd party install tool like "WinNTSetup".

**Comment by myrsloik** [comment]
> First, I mean an official build of Vapoursynth R53 that uses python 3.8.9.

I understand what you meant. Feel free to make your own 3.8 builds if you want to, it's open source. I'll link to them and answer any build related questions if you're interested.

> Second. Windows 7 Still have ESU till Jan. 2023, If use Windows Embedded PosReady 7's patch can stayed to Oct. 2024.

I don't support obsolete versions of windows since it adds a time cost to development. You're getting these builds and code for free. If you want to pay for enterprise level support with custom builds that can probably be arranged either by me or possibly by one of the other big contributors.

Note that Windows Embedded PosReady 7 was never supported at all since that'd mean you're encoding on CASH REGISTERS.
