### ISSUE TITLE
Cython memory views don't keep a reference to the underlying VSFrame

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#710]
Exposed with the huge cython cleanup where frame references get freed faster.

**Comment by Kamekameha** [comment]
When using Cython arrays (`cython.view.array`, as opposed to `cython.view.memoryview`) to wrap the raw pointers there's not much one could do about it.

Using `VideoPlane` instead would keep the reference around.  However, I've in the past said that I'm not exactly a fan of `get_read_array()`/`get_write_array()` and how they expose memory to Python, so I'd rather not attempt to make them work with `VideoPlane`.

Also, I've been meaning to rewrite the implementation of `VideoPlane` since I haven't been satisfied with my attempt for quite a while.  Maybe I should get to that.

(By the way, the issue title should reflect that it's **Cython** memoryviews that ultimately don't hold references to the frame, not Python's.)

**Comment by myrsloik** [comment]
If you fix VideoPlane quickly I may end up removing get_read_array+get_write_array.

**Comment by Kamekameha** [comment]
Okay, I'll see what I can do.

**Comment by Kamekameha** [comment]
So I noticed that, whether or not a reference to the frame object is held, a frame's copy-on-write can still invalidate pointers already exposed to Python.  Maybe I should open a separate issue about it.

**Comment by myrsloik** [comment]
It only happens in the very specific case where you make a frame writable with copyFrame() (or newvideoframe2 but I don't think that is a reachable function from cython), get a read pointer to the new frame and after that get a write pointer.

**Comment by Kamekameha** [comment]
I still believe we shouldn't let that happen, especially on the Python side of things.
