### ISSUE TITLE
Things that need APIv4 support

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#718]
Filters with nfMakeLinear:
d2vsource (fixed branch here https://github.com/dwbuiten/d2vsource/tree/newffmpeg)
l-smash (fixed branch here https://github.com/AkarinVS/L-SMASH-Works/tree/vs-api4)
DG stuff
https://github.com/dubhater/vapoursynth-tivtc
https://github.com/Hinterwaeldlers/vapoursynth-hqdn3d
https://github.com/dubhater/vapoursynth-cnr2
VMAF (probably doesn't benefit from it anyway)

Applications that use compat formats:
https://github.com/Endilll/vapoursynth-preview

**Comment by AkarinVS** [comment]
Is there any plan to have a compat library that makes it easier for a
filter to support both API versions? I think v3 and v4 API will co-exist
for a long time (see how long it takes Python to drop support for Python
2.7.)

Regarding compat formats, are there any existing filters that could convert
VS's planar RGB format to non-planar RGB formats expected by various
imaging/GUI libraries? I tried to port vs-preview, but couldn't find an
existing solution, so I hacked one together with lexpr and COMPATBGR32 is
emulated with integer 32-bit gray clips. Needless to say, the code is ugly.
https://github.com/AkarinVS/vapoursynth-preview/blob/dcea4ba33a5856efe58fc4d28c1008465e54f887/vspreview/core/types.py#L784
.
As I don't think Qt supports planar RGB image formats, I'd really like a
standard filter that could do the conversion so that users do not need to
install any additional plugins to use Python based previewers.

Additionally, it seems if v4 API is enabled, compat format support is
completely removed, even for plugins that still use the v3 API, which still
exposes those format constants.

**Comment by myrsloik** [comment]
As a consumer you can support both versions easily using a subset of the v3 API. There are no further tricks planned. 98% of the filter api and 100% of the vsscript v3 apis are supported and will be for several years until everything is converted.

Note that compat formats were never available in normal filters and only ~10 simple core filters ever supported them. Plugins couldn't even accept compat format nodes as input so none of them exist. I've always been very clear about them going away the day they don't fill a purpose anymore.

Either way, packing some bytes in a temporary buffer is trivial and this will fixed in no time.

**Comment by theChaosCoder** [comment]
`AttributeError: module 'vapoursynth' has no attribute 'YCOCG'`

YCOCG is used in:
- fvsfunc
- mvsfunc
- muvsfunc
- nnedi3_resample
- vsutil

**Comment by sekrit-twc** [comment]
It's always been the case that, because of differences in padding/alignment, it was not possible to directly use a VS FrameRef as a bitmap in GUI frameworks. What is new is that instead of only copying the bits, the application is also responsible for swizzling the components. There is already a helper library, p2p (used within VS), that can handle this conversion.

**Comment by AkarinVS** [comment]
On Tue, Jul 27, 2021 at 7:32 PM sekrit-twc ***@***.***> wrote:

> It's always been the case that, because of differences in
> padding/alignment, it was not possible to directly use a VS FrameRef as a
> bitmap in GUI frameworks. What is new is that instead of only copying the
> bits, the application is also responsible for swizzling the components.
> There is already a helper library, p2p (used within VS), that can handle
> this conversion.
>
With COMPATBGR32, vs-preview is able to directly use the frame memory to
construct a QImage without copying.
https://doc.qt.io/qt-5/qimage.html#QImage-6

**Comment by sekrit-twc** [comment]
You can use `QImage::QImage(int width, int height, QImage::Format format)` and convert the plane using p2p, which is what VS was doing prior to v4.

**Comment by theChaosCoder** [comment]
muvsfunc was updated https://github.com/WolframRhodium/muvsfunc/commit/203a8c066c1bf9830dd2893d061cf9269ecb1762

**Comment by sekrit-twc** [comment]
@AkarinVS 
>            return vs.core.akarin.Expr([ vs.core.std.ShufflePlanes(vs_output, i, vs.GRAY) for i in range(3) ], f'x {0x10000} * y {0x100} * + z + {0xff} {0x1000000} * +', fmt, opt=1)

````
There's another way to do this entirely within VS:
clip = core.std.BlankClip(color=[64, 128, 192])
clip = core.std.Transpose(clip)

r = core.std.ShufflePlanes(clip, 0, vs.GRAY)
g = core.std.ShufflePlanes(clip, 1, vs.GRAY)
b = core.std.ShufflePlanes(clip, 2, vs.GRAY)
a = core.std.BlankClip(clip, format=vs.GRAY8, color=255)

br = core.std.DoubleWeave(core.std.Interleave([b, r]), tff=True).std.SelectEvery(2, 0)
ga = core.std.DoubleWeave(core.std.Interleave([g, a]), tff=True).std.SelectEvery(2, 0)
bgra = core.std.DoubleWeave(core.std.Interleave([br, ga]), tff=True).std.SelectEvery(2, 0)
bgra = core.std.Transpose(bgra)
bgra.set_output()
````

**Comment by CrendKing** [comment]
Just to chime in about the compat formats. I'm the author of [avisynth_filter](https://github.com/CrendKing/avisynth_filter), which injects VapourSynth into DirectShow graph. Since DirectShow supports YUY2, and the few non-YUV formats DS natively supports are the packed RGB formats, my filter currently [has them](https://github.com/CrendKing/avisynth_filter/blob/master/vapoursynth_filter/src/format.cpp). If VapourSynth completely drops these two formats, it's not end of the world, but some format conversions will be needed for videos encoded that way, which depending on the bitrate, could hurt performance a bit.

**Comment by theChaosCoder** [comment]
nfMakeLinear:
- https://github.com/dubhater/vapoursynth-cnr2/blob/1f2c901396b35b2876a3771d5f462c60b1933ce3/src/cnr2.c#L315
- https://github.com/dubhater/vapoursynth-tivtc/blob/1713095068d18a2fe93598aaabd7e53e12163e03/src/PluginInit.cpp#L301
- https://github.com/HomeOfVapourSynthEvolution/VapourSynth-VMAF/blob/ad429e7708fb44614f5c675b8620a6094de05276/VMAF/VMAF.cpp#L277
- https://github.com/Hinterwaeldlers/vapoursynth-hqdn3d/blob/eb820cb23f7dc47eb67ea95def8a09ab69251d30/src/hqdn3d.cpp#L398

Nim wrapper
- https://github.com/mantielero/VapourSynth.nim/blob/ac36fffa1f1b020f71fb8a863749c99f9e8df138/src/wrapper/VapourSynth_wrapper.nim#L57

**Comment by myrsloik** [comment]
I don't think VMAF actually benefits from the flag so I'll skip that in the list. The nim wrapper is simply a complete api 3 wrapper so that's normal too. The rest have been added.

**Comment by theChaosCoder** [comment]
Replace one cnr2 with tivtc in your list :)

**Comment by quietvoid** [comment]
Probably not very used but https://github.com/quietvoid/vspreview-rs also uses compat format.
Unfortunately `vapoursynth-rs` has trouble with RGB24 on 4:3, and even non mod 8 resolutions with compat as well.

**Comment by AkarinVS** [comment]
Not sure if upstream mvsfunc still accepts PR, but we have maintained a
fork here:
https://github.com/AmusementClub/mvsfunc/
it should be compatible with both v3 and v4 API (along with some optional
lexpr optimizations.)

**Comment by YomikoR** [comment]
As of today, AvsPmod is alive provided the video output is in RGB24 / RGB30 / RGB48.

**Comment by myrsloik** [comment]
Interesting. I guess mvsfunc should be considered done too. Making good progress. Here's my own updated branch of d2vsource https://github.com/dwbuiten/d2vsource/tree/newffmpeg that I unfortunately couldn't fully test since it gets miscompiled with my vs2019. Help with testing welcome so it can be merged and crossed off too.

**Comment by AkarinVS** [comment]
nnedi3_resample is done as well:
https://github.com/AmusementClub/VapourSynth-script/blob/master/nnedi3_resample.py

**Comment by myrsloik** [comment]
> nnedi3_resample is done as well: https://github.com/AmusementClub/VapourSynth-script/blob/master/nnedi3_resample.py

There's another improved version by Selur here that adds some options if you want to go for making the ultimate fork. https://github.com/Selur/VapoursynthScriptsInHybrid/blob/master/nnedi3_resample.py

**Comment by YomikoR** [comment]
> Regarding compat formats, are there any existing filters that could convert
VS's planar RGB format to non-planar RGB formats expected by various
imaging/GUI libraries? 

If it's for vs-preview, numpy is sufficient. [My approach](https://github.com/YomikoR/vapoursynth-preview/blob/api-v4-numpy-10-bit/vspreview/core/types.py#L801)

**Comment by myrsloik** [comment]
That's a not too horrible way to write it. Interesting. The only thing I'm worried about now is the vsedit(2?) support and maybe l-smash where I haven't gotten any kind of reaction from the authors at all.

**Comment by AkarinVS** [comment]
lsmas has a preliminary port to v4 API:
https://github.com/AkarinVS/L-SMASH-Works/tree/vs-api4
(due to limited resources, I opted to release separate versions for API v3
and v4 and hopefully we could migrate to v4 fairly soon.)
However, it still does not make use of the new cacheFrame API, so its
performance is horrible; but I'm working on this issue now.

The audio support is tracked as
https://github.com/AkarinVS/L-SMASH-Works/issues/5, but I do not have plans
to tackle it any time soon.
(Using BAS should suffice in the interim, I don't feel like lsmas need
audio support. Please comment on the linked issue if you have reasons for
lsmas to get its own audio filter.)

**Comment by myrsloik** [comment]
Speaking of migrating things. I think you could make a simple search and replace script that does 90% of the work of converting normal filters to the new api. Do you think there's any interest in creating this?

**Comment by theChaosCoder** [comment]
The first vseditor with v4 support has appeared https://github.com/YomikoR/VapourSynth-Editor

**Comment by Ichunjo** [comment]
No one mentionned the rename of `Format` to `VideoFormat`. It breaks at least my func [vardefunc](https://github.com/Ichunjo/vardefunc) and [EoEfunc](https://gitlab.com/arjraj/EoEfunc) since we import it from vapoursynth.

**Comment by theChaosCoder** [comment]
Found another "source" plugin. This one does not work with api4 at all. https://github.com/ifb/vapoursynth-colorbars/issues/7
